### ISSUE TITLE
Syntax error when running main.py

### ISSUE THREAD

**Issue by lothkang** [lossless1024/fansly-dl#1]
Hi, I'm trying to run it on Ubuntu 22.04.1 LTS
I followed the instructions in Readme.md and I get the following error message when running python3 ./main.py:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/home/weylyn1/Letöltések/fansly-dl/main.py", line 11, in <module>
    config = json.load(f)
  File "/usr/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 5 column 15 (char 155)

Here's the contents of my [config.json](https://pastebin.com/yNPrucY0).

**Comment by insomniacdev212** [comment]
the token is supposed to be only the "token" string
