### ISSUE TITLE
Unable to download anyting

### ISSUE THREAD

**Issue by lothkang** [lossless1024/fansly-dl#3]
I'm trying to run the latest version on Windows 11 Home with Pyton 3.12 and I get the following error:
```
PS E:\FANSLY> python3.12.exe .\main.py
2024-04-21 19:50:18,309 - root - INFO - Fetching user data
Traceback (most recent call last):
  File "E:\FANSLY\main.py", line 191, in <module>
    main()
  File "E:\FANSLY\main.py", line 146, in main
    accounts = Fetch('account?ids=' + ','.join(accountIds), paged=False)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\FANSLY\main.py", line 37, in __init__
    self.fetch_more()
  File "E:\FANSLY\main.py", line 73, in fetch_more
    if not response['success']:
           ~~~~~~~~^^^^^^^^^^^
KeyError: 'success'
```

```
PS E:\FANSLY> python.exe .\main.py
2024-04-21 19:51:26,993 - root - INFO - Fetching user data
2024-04-21 19:51:29,396 - root - INFO - Downloading account therealtoriann
E:\FANSLY\main.py:121: DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.fromtimestamp(timestamp, datetime.UTC).
  filename = datetime.datetime.utcfromtimestamp(data['createdAt']).strftime('%Y%m%d_%H%M%S_') + cdn_filename
Traceback (most recent call last):
  File "E:\FANSLY\main.py", line 191, in <module>
    main()
  File "E:\FANSLY\main.py", line 161, in main
    if not download_media(data, folder):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\FANSLY\main.py", line 130, in download_media
    with open(full_dl_path, 'wb') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'dl/therealtoriann/20240326_135055_629005910374621184.jpeg'
```

**Comment by IndiePay** [comment]
This is not update.
Try https://github.com/IndiePay/FanslyDownloader still work.
